#!/bin/bash

# this shell script compile and run the c program
# usage $ ./compileNrun filename.c var1 var2 ...

mkdir -p -v build

cname=$1
filename="${cname%.*}"
shift
vars=$@

gcc "${filename}.c" -o "./build/$filename"

./build/$filename $vars
